In [2]:
import numpy as np

# Basics

In [11]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
# Get dimension
b.ndim

2

In [22]:
# Get Shape
b.shape

(2, 3)

In [23]:
# Get type
a.dtype

dtype('int32')

In [24]:
# Get size, It will show the number of bytes of data type
a.itemsize 

4

In [26]:
# Get total size, shows no. of elements
b.size

6

# Accessing/Changing specific elements, rows, columns, etc.

In [29]:
a = np.array([[1,2,3,4,5,6,7],[3,4,5,6,7,8,9]])
print(a)

[[1 2 3 4 5 6 7]
 [3 4 5 6 7 8 9]]


In [30]:
# Get a specific element
a[1,5]

8

In [35]:
# Get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [36]:
# Get a specific column
print(a[:,1])

[2 4]


In [37]:
# Get nuumbers through start index, stop index
a[0,1:4]

array([2, 3, 4])

In [38]:
# Changing element
a[1,3] = 40
print(a)

[[ 1  2  3  4  5  6  7]
 [ 3  4  5 40  7  8  9]]


# Initializing different types of arrays

In [43]:
# All 0's
# Here we are showing example of 3d array of 0's
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
# all 1's -- 2 Dimensional example
np.ones((2,3), dtype='int16')

[[1 1 1]
 [1 1 1]]


In [48]:
 # any other number
np.full((2,2),11)

array([[11, 11],
       [11, 11]])

In [49]:
# using other array, it will take shape of the array given as argument
b = np.array([[1,2,3,4,5,6,7],[3,4,5,6,7,8,9]]) 
np.full_like(b,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [50]:
# Random decimal numbers
np.random.rand(3,3)

array([[0.74904553, 0.72848709, 0.17230446],
       [0.80161052, 0.72759037, 0.1201237 ],
       [0.58882622, 0.25328627, 0.92713922]])

In [3]:
# Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Mathamatics

In [9]:
a = np.array([1,2,3,4,5])
a + 2

array([3, 4, 5, 6, 7])

In [10]:
a - 2

array([-1,  0,  1,  2,  3])

In [11]:
a * 2

array([ 2,  4,  6,  8, 10])

In [12]:
a ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [13]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [14]:
# Take the sign of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [15]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

# Linear Algebra

In [18]:
a = np.full((3,4),2)
b = np.full((4,3),5)
print(a)
print(b)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [20]:
np.matmul(a,b)

array([[40, 40, 40],
       [40, 40, 40],
       [40, 40, 40]])

In [23]:
# Find the determinant
c = np.identity(3)
#print(c)
np.linalg.det(c) #linalg is module for linear algebra

1.0

# Statistics

In [24]:
stats = np.array([[1,2,3],[7,9,11]])

In [25]:
np.min(stats)

1

In [26]:
np.max(stats)

11

In [28]:
np.min(stats,axis=0) # axis = 0 means columns wise minimum

array([1, 2, 3])

In [30]:
np.max(stats, axis = 1) # axis = 1 means row wise

array([ 3, 11])

In [31]:
np.sum(stats)

33

In [34]:
np.sum(stats,axis = 0)

array([ 8, 11, 14])

In [35]:
# Vertical Stacking
v1 = np.array([1,2,3])
v2 = np.array([3,4,5])

In [37]:
np.vstack([v1,v2])

array([[1, 2, 3],
       [3, 4, 5]])

In [38]:
np.hstack([v1,v2])

array([1, 2, 3, 3, 4, 5])

# Load data From file

In [40]:
filedata = np.genfromtxt('numpy_data.txt',delimiter=',')

In [41]:
filedata = filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking

In [42]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [43]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [45]:
np.any(filedata > 50,axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])