In [4]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('4.1_tips.csv')

In [4]:
df

total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
5         25.29  4.71     No   Sun  Dinner     4
6          8.77  2.00     No   Sun  Dinner     2
7         26.88  3.12     No   Sun  Dinner     4
8         15.04  1.96     No   Sun  Dinner     2
9         14.78  3.23     No   Sun  Dinner     2
10        10.27  1.71     No   Sun  Dinner     2
11        35.26  5.00     No   Sun  Dinner     4
12        15.42  1.57     No   Sun  Dinner     2
13        18.43  3.00     No   Sun  Dinner     4
14        14.83  3.02     No   Sun  Dinner     2
15        21.58  3.92     No   Sun  Dinner     2
16        10.33  1.67     No   Sun  Dinner     3
17        16.29  3.71     No   Sun  Dinner     3
18        16.97  3.50     No   Sun  Dinner     3
19        20.65  3.35     No   Sat  Dinner     3
20        17.92  4.08     No   Sat  Dinner     2
21        20.29  2.75     No   Sat  Dinner     2
22        15.77  2.23     No   Sat  Dinner     2
23        39.42  7.58     No   Sat  Dinner     4
24        19.82  3.18     No   Sat  Dinner     2
25        17.81  2.34     No   Sat  Dinner     4
26        13.37  2.00     No   Sat  Dinner     2
27        12.69  2.00     No   Sat  Dinner     2
28        21.70  4.30     No   Sat  Dinner     2
29        19.65  3.00     No   Sat  Dinner     2
..          ...   ...    ...   ...     ...   ...
214       28.17  6.50    Yes   Sat  Dinner     3
215       12.90  1.10    Yes   Sat  Dinner     2
216       28.15  3.00    Yes   Sat  Dinner     5
217       11.59  1.50    Yes   Sat  Dinner     2
218        7.74  1.44    Yes   Sat  Dinner     2
219       30.14  3.09    Yes   Sat  Dinner     4
220       12.16  2.20    Yes   Fri   Lunch     2
221       13.42  3.48    Yes   Fri   Lunch     2
222        8.58  1.92    Yes   Fri   Lunch     1
223       15.98  3.00     No   Fri   Lunch     3
224       13.42  1.58    Yes   Fri   Lunch     2
225       16.27  2.50    Yes   Fri   Lunch     2
226       10.09  2.00    Yes   Fri   Lunch     2
227       20.45  3.00     No   Sat  Dinner     4
228       13.28  2.72     No   Sat  Dinner     2
229       22.12  2.88    Yes   Sat  Dinner     2
230       24.01  2.00    Yes   Sat  Dinner     4
231       15.69  3.00    Yes   Sat  Dinner     3
232       11.61  3.39     No   Sat  Dinner     2
233       10.77  1.47     No   Sat  Dinner     2
234       15.53  3.00    Yes   Sat  Dinner     2
235       10.07  1.25     No   Sat  Dinner     2
236       12.60  1.00    Yes   Sat  Dinner     2
237       32.83  1.17    Yes   Sat  Dinner     2
238       35.83  4.67     No   Sat  Dinner     3
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [13]:
k1_means = df.groupby('day').mean().add_prefix('mean_')

In [14]:
k1_means

mean_total_bill  mean_tip  mean_size
day                                       
Fri         17.151579  2.734737   2.105263
Sat         20.441379  2.993103   2.517241
Sun         21.410000  3.255132   2.842105
Thur        17.682742  2.771452   2.451613

In [21]:
pd.merge(df,k1_means,left_on='day',right_index=True)

total_bill   tip smoker   day    time  size  mean_total_bill  mean_tip  \
0         16.99  1.01     No   Sun  Dinner     2        21.410000  3.255132   
1         10.34  1.66     No   Sun  Dinner     3        21.410000  3.255132   
2         21.01  3.50     No   Sun  Dinner     3        21.410000  3.255132   
3         23.68  3.31     No   Sun  Dinner     2        21.410000  3.255132   
4         24.59  3.61     No   Sun  Dinner     4        21.410000  3.255132   
5         25.29  4.71     No   Sun  Dinner     4        21.410000  3.255132   
6          8.77  2.00     No   Sun  Dinner     2        21.410000  3.255132   
7         26.88  3.12     No   Sun  Dinner     4        21.410000  3.255132   
8         15.04  1.96     No   Sun  Dinner     2        21.410000  3.255132   
9         14.78  3.23     No   Sun  Dinner     2        21.410000  3.255132   
10        10.27  1.71     No   Sun  Dinner     2        21.410000  3.255132   
11        35.26  5.00     No   Sun  Dinner     4        21.410000  3.255132   
12        15.42  1.57     No   Sun  Dinner     2        21.410000  3.255132   
13        18.43  3.00     No   Sun  Dinner     4        21.410000  3.255132   
14        14.83  3.02     No   Sun  Dinner     2        21.410000  3.255132   
15        21.58  3.92     No   Sun  Dinner     2        21.410000  3.255132   
16        10.33  1.67     No   Sun  Dinner     3        21.410000  3.255132   
17        16.29  3.71     No   Sun  Dinner     3        21.410000  3.255132   
18        16.97  3.50     No   Sun  Dinner     3        21.410000  3.255132   
41        17.46  2.54     No   Sun  Dinner     2        21.410000  3.255132   
42        13.94  3.06     No   Sun  Dinner     2        21.410000  3.255132   
43         9.68  1.32     No   Sun  Dinner     2        21.410000  3.255132   
44        30.40  5.60     No   Sun  Dinner     4        21.410000  3.255132   
45        18.29  3.00     No   Sun  Dinner     2        21.410000  3.255132   
46        22.23  5.00     No   Sun  Dinner     2        21.410000  3.255132   
47        32.40  6.00     No   Sun  Dinner     4        21.410000  3.255132   
48        28.55  2.05     No   Sun  Dinner     3        21.410000  3.255132   
49        18.04  3.00     No   Sun  Dinner     2        21.410000  3.255132   
50        12.54  2.50     No   Sun  Dinner     2        21.410000  3.255132   
51        10.29  2.60     No   Sun  Dinner     2        21.410000  3.255132   
..          ...   ...    ...   ...     ...   ...              ...       ...   
196       10.34  2.00    Yes  Thur   Lunch     2        17.682742  2.771452   
197       43.11  5.00    Yes  Thur   Lunch     4        17.682742  2.771452   
198       13.00  2.00    Yes  Thur   Lunch     2        17.682742  2.771452   
199       13.51  2.00    Yes  Thur   Lunch     2        17.682742  2.771452   
200       18.71  4.00    Yes  Thur   Lunch     3        17.682742  2.771452   
201       12.74  2.01    Yes  Thur   Lunch     2        17.682742  2.771452   
202       13.00  2.00    Yes  Thur   Lunch     2        17.682742  2.771452   
203       16.40  2.50    Yes  Thur   Lunch     2        17.682742  2.771452   
204       20.53  4.00    Yes  Thur   Lunch     4        17.682742  2.771452   
205       16.47  3.23    Yes  Thur   Lunch     3        17.682742  2.771452   
243       18.78  3.00     No  Thur  Dinner     2        17.682742  2.771452   
90        28.97  3.00    Yes   Fri  Dinner     2        17.151579  2.734737   
91        22.49  3.50     No   Fri  Dinner     2        17.151579  2.734737   
92         5.75  1.00    Yes   Fri  Dinner     2        17.151579  2.734737   
93        16.32  4.30    Yes   Fri  Dinner     2        17.151579  2.734737   
94        22.75  3.25     No   Fri  Dinner     2        17.151579  2.734737   
95        40.17  4.73    Yes   Fri  Dinner     4        17.151579  2.734737   
96        27.28  4.00    Yes   Fri  Dinner     2        17.151579  2.734737   
97        12.03  1.50    Yes   Fri  Dinner     2       

In [16]:
key = ['smoker','day']

In [17]:
df.groupby(key).mean()

total_bill       tip      size
smoker day                                 
No     Fri    18.420000  2.812500  2.250000
       Sat    19.661778  3.102889  2.555556
       Sun    20.506667  3.167895  2.929825
       Thur   17.113111  2.673778  2.488889
Yes    Fri    16.813333  2.714000  2.066667
       Sat    21.276667  2.875476  2.476190
       Sun    24.120000  3.516842  2.578947
       Thur   19.190588  3.030000  2.352941

In [18]:
df.groupby(key).transform(np.mean)

total_bill       tip      size
0     20.506667  3.167895  2.929825
1     20.506667  3.167895  2.929825
2     20.506667  3.167895  2.929825
3     20.506667  3.167895  2.929825
4     20.506667  3.167895  2.929825
5     20.506667  3.167895  2.929825
6     20.506667  3.167895  2.929825
7     20.506667  3.167895  2.929825
8     20.506667  3.167895  2.929825
9     20.506667  3.167895  2.929825
10    20.506667  3.167895  2.929825
11    20.506667  3.167895  2.929825
12    20.506667  3.167895  2.929825
13    20.506667  3.167895  2.929825
14    20.506667  3.167895  2.929825
15    20.506667  3.167895  2.929825
16    20.506667  3.167895  2.929825
17    20.506667  3.167895  2.929825
18    20.506667  3.167895  2.929825
19    19.661778  3.102889  2.555556
20    19.661778  3.102889  2.555556
21    19.661778  3.102889  2.555556
22    19.661778  3.102889  2.555556
23    19.661778  3.102889  2.555556
24    19.661778  3.102889  2.555556
25    19.661778  3.102889  2.555556
26    19.661778  3.102889  2.555556
27    19.661778  3.102889  2.555556
28    19.661778  3.102889  2.555556
29    19.661778  3.102889  2.555556
..          ...       ...       ...
214   21.276667  2.875476  2.476190
215   21.276667  2.875476  2.476190
216   21.276667  2.875476  2.476190
217   21.276667  2.875476  2.476190
218   21.276667  2.875476  2.476190
219   21.276667  2.875476  2.476190
220   16.813333  2.714000  2.066667
221   16.813333  2.714000  2.066667
222   16.813333  2.714000  2.066667
223   18.420000  2.812500  2.250000
224   16.813333  2.714000  2.066667
225   16.813333  2.714000  2.066667
226   16.813333  2.714000  2.066667
227   19.661778  3.102889  2.555556
228   19.661778  3.102889  2.555556
229   21.276667  2.875476  2.476190
230   21.276667  2.875476  2.476190
231   21.276667  2.875476  2.476190
232   19.661778  3.102889  2.555556
233   19.661778  3.102889  2.555556
234   21.276667  2.875476  2.476190
235   19.661778  3.102889  2.555556
236   21.276667  2.875476  2.476190
237   21.276667  2.875476  2.476190
238   19.661778  3.102889  2.555556
239   19.661778  3.102889  2.555556
240   21.276667  2.875476  2.476190
241   21.276667  2.875476  2.476190
242   19.661778  3.102889  2.555556
243   17.113111  2.673778  2.488889

[244 rows x 3 columns]

In [47]:
def top(df,n=5,column='total_bill'):
    return df.sort_values(by=column)[-n:]
df.groupby('smoker').apply(top)

total_bill    tip smoker   day    time  size
smoker                                                  
No     23        39.42   7.58     No   Sat  Dinner     4
       142       41.19   5.00     No  Thur   Lunch     5
       156       48.17   5.00     No   Sun  Dinner     6
       59        48.27   6.73     No   Sat  Dinner     4
       212       48.33   9.00     No   Sat  Dinner     4
Yes    184       40.55   3.00    Yes   Sun  Dinner     2
       197       43.11   5.00    Yes  Thur   Lunch     4
       102       44.30   2.50    Yes   Sat  Dinner     3
       182       45.35   3.50    Yes   Sun  Dinner     3
       170       50.81  10.00    Yes   Sat  Dinner     3

In [48]:
df.groupby(['smoker','day']).apply(top)

total_bill    tip smoker   day    time  size
smoker day                                                   
No     Fri  99        12.46   1.50     No   Fri  Dinner     2
            223       15.98   3.00     No   Fri   Lunch     3
            91        22.49   3.50     No   Fri  Dinner     2
            94        22.75   3.25     No   Fri  Dinner     2
       Sat  39        31.27   5.00     No   Sat  Dinner     3
            238       35.83   4.67     No   Sat  Dinner     3
            23        39.42   7.58     No   Sat  Dinner     4
            59        48.27   6.73     No   Sat  Dinner     4
            212       48.33   9.00     No   Sat  Dinner     4
       Sun  47        32.40   6.00     No   Sun  Dinner     4
            52        34.81   5.20     No   Sun  Dinner     4
            11        35.26   5.00     No   Sun  Dinner     4
            112       38.07   4.00     No   Sun  Dinner     3
            156       48.17   5.00     No   Sun  Dinner     6
       Thur 77        27.20   4.00     No  Thur   Lunch     4
            125       29.80   4.20     No  Thur   Lunch     6
            141       34.30   6.70     No  Thur   Lunch     6
            85        34.83   5.17     No  Thur   Lunch     4
            142       41.19   5.00     No  Thur   Lunch     5
Yes    Fri  93        16.32   4.30    Yes   Fri  Dinner     2
            98        21.01   3.00    Yes   Fri  Dinner     2
            96        27.28   4.00    Yes   Fri  Dinner     2
            90        28.97   3.00    Yes   Fri  Dinner     2
            95        40.17   4.73    Yes   Fri  Dinner     4
       Sat  237       32.83   1.17    Yes   Sat  Dinner     2
            56        38.01   3.00    Yes   Sat  Dinner     4
            207       38.73   3.00    Yes   Sat  Dinner     4
            102       44.30   2.50    Yes   Sat  Dinner     3
            170       50.81  10.00    Yes   Sat  Dinner     3
       Sun  175       32.90   3.11    Yes   Sun  Dinner     2
            179       34.63   3.55    Yes   Sun  Dinner     2
            180       34.65   3.68    Yes   Sun  Dinner     4
            184       40.55   3.00    Yes   Sun  Dinner     2
            182       45.35   3.50    Yes   Sun  Dinner     3
       Thur 191       19.81   4.19    Yes  Thur   Lunch     2
            204       20.53   4.00    Yes  Thur   Lunch     4
            192       28.44   2.56    Yes  Thur   Lunch     2
            83        32.68   5.00    Yes  Thur   Lunch     2
            197       43.11   5.00    Yes  Thur   Lunch     4

In [1]:
s = pd.Series(np.random.randn(6))

NameError: name 'pd' is not defined

In [2]:
s

NameError: name 's' is not defined

In [54]:
s[::2] = np.nan

In [56]:
s.fillna(s.mean())

0    1.431512
1    1.777854
2    1.431512
3   -0.269554
4    1.431512
5    2.786236
dtype: float64

In [58]:
df.pivot_table(index=['day','smoker'])

size       tip  total_bill
day  smoker                                
Fri  No      2.250000  2.812500   18.420000
     Yes     2.066667  2.714000   16.813333
Sat  No      2.555556  3.102889   19.661778
     Yes     2.476190  2.875476   21.276667
Sun  No      2.929825  3.167895   20.506667
     Yes     2.578947  3.516842   24.120000
Thur No      2.488889  2.673778   17.113111
     Yes     2.352941  3.030000   19.190588

In [60]:
df.pivot_table(['tip','size'],index=['time','day'],columns='smoker')

size                 tip          
smoker             No       Yes        No       Yes
time   day                                         
Dinner Fri   2.000000  2.222222  2.750000  3.003333
       Sat   2.555556  2.476190  3.102889  2.875476
       Sun   2.929825  2.578947  3.167895  3.516842
       Thur  2.000000       NaN  3.000000       NaN
Lunch  Fri   3.000000  1.833333  3.000000  2.280000
       Thur  2.500000  2.352941  2.666364  3.030000

In [62]:
#For Total, Margins used for all
df.pivot_table(['tip','size'],index=['time','day'],columns='smoker',margins=True)

size                           tip                    
smoker             No       Yes       All        No       Yes       All
time   day                                                             
Dinner Fri   2.000000  2.222222  2.166667  2.750000  3.003333  2.940000
       Sat   2.555556  2.476190  2.517241  3.102889  2.875476  2.993103
       Sun   2.929825  2.578947  2.842105  3.167895  3.516842  3.255132
       Thur  2.000000       NaN  2.000000  3.000000       NaN  3.000000
Lunch  Fri   3.000000  1.833333  2.000000  3.000000  2.280000  2.382857
       Thur  2.500000  2.352941  2.459016  2.666364  3.030000  2.767705
All          2.668874  2.408602  2.569672  2.991854  3.008710  2.998279

In [63]:
#For Total
df.pivot_table(['tip','size'],index=['time','day'],columns='smoker',aggfunc=len,margins=True)

size               tip             
smoker          No   Yes  All     No   Yes    All
time   day                                       
Dinner Fri     3.0   9.0   12    3.0   9.0   12.0
       Sat    45.0  42.0   87   45.0  42.0   87.0
       Sun    57.0  19.0   76   57.0  19.0   76.0
       Thur    1.0   NaN    1    1.0   NaN    1.0
Lunch  Fri     1.0   6.0    7    1.0   6.0    7.0
       Thur   44.0  17.0   61   44.0  17.0   61.0
All          151.0  93.0  244  151.0  93.0  244.0

In [64]:
#For Total
df.pivot_table(['tip','size'],index=['time','day'],columns='smoker',aggfunc=sum,fill_value=0)

size          tip        
smoker        No  Yes      No     Yes
time   day                           
Dinner Fri     6   20    8.25   27.03
       Sat   115  104  139.63  120.77
       Sun   167   49  180.57   66.82
       Thur    2    0    3.00    0.00
Lunch  Fri     3   11    3.00   13.68
       Thur  110   40  117.32   51.51

### Cross Tabulation using Pandas

In [65]:
#Crosstab only shows count, aggregate function can not be used with crosstab
pd.crosstab([df.time,df.day],df.smoker,margins=True)

smoker        No  Yes  All
time   day                
Dinner Fri     3    9   12
       Sat    45   42   87
       Sun    57   19   76
       Thur    1    0    1
Lunch  Fri     1    6    7
       Thur   44   17   61
All          151   93  244

## Data Aggregation

In [82]:
grouped = df.groupby(['smoker'])

In [83]:
means = df.groupby(['smoker','day']).mean()

In [84]:
means

total_bill       tip      size
smoker day                                 
No     Fri    18.420000  2.812500  2.250000
       Sat    19.661778  3.102889  2.555556
       Sun    20.506667  3.167895  2.929825
       Thur   17.113111  2.673778  2.488889
Yes    Fri    16.813333  2.714000  2.066667
       Sat    21.276667  2.875476  2.476190
       Sun    24.120000  3.516842  2.578947
       Thur   19.190588  3.030000  2.352941

In [85]:
means.unstack()

total_bill                                      tip            \
day           Fri        Sat        Sun       Thur     Fri       Sat   
smoker                                                                 
No      18.420000  19.661778  20.506667  17.113111  2.8125  3.102889   
Yes     16.813333  21.276667  24.120000  19.190588  2.7140  2.875476   

                                size                                
day          Sun      Thur       Fri       Sat       Sun      Thur  
smoker                                                              
No      3.167895  2.673778  2.250000  2.555556  2.929825  2.488889  
Yes     3.516842  3.030000  2.066667  2.476190  2.578947  2.352941

In [87]:
df.dtypes

total_bill    float64
tip           float64
smoker         object
day            object
time           object
size            int64
dtype: object

In [93]:
People=pd.DataFrame(np.random.randn(5,5),columns=['a','b','c','d','e'],index=['joe','bill','steve','wes','jimmy'])

In [94]:
People

a         b         c         d         e
joe   -0.004602 -1.255300 -0.894322 -0.327628  1.054381
bill  -1.065955 -0.073396  0.584588  0.240412 -1.023564
steve -0.680414  2.788142  0.986700 -0.564726 -1.242639
wes    0.325872  1.031210 -1.524615  0.465961 -0.456441
jimmy  0.749239 -0.678294  1.795970 -0.954082  0.513334

In [95]:
People.groupby(len).sum()

a         b         c         d         e
3  0.321270 -0.224091 -2.418938  0.138333  0.597940
4 -1.065955 -0.073396  0.584588  0.240412 -1.023564
5  0.068825  2.109848  2.782670 -1.518807 -0.729305

In [100]:
key_list=['one','one','one','two','two']

In [101]:
People.groupby([len,key_list]).min()

a         b         c         d         e
3 one -0.004602 -1.255300 -0.894322 -0.327628  1.054381
  two  0.325872  1.031210 -1.524615  0.465961 -0.456441
4 one -1.065955 -0.073396  0.584588  0.240412 -1.023564
5 one -0.680414       NaN       NaN -0.564726 -1.242639
  two  0.749239 -0.678294  1.795970 -0.954082  0.513334

In [102]:
Columns=pd.MultiIndex.from_arrays([['US','US','US','JP','JP'],[1,3,5,1,3]],names=['city','tenor'])

In [104]:
Columns

MultiIndex(levels=[['JP', 'US'], [1, 3, 5]],
           codes=[[1, 1, 1, 0, 0], [0, 1, 2, 0, 1]],
           names=['city', 'tenor'])

In [106]:
H=pd.DataFrame(np.random.randn(4,5),columns=Columns)

In [107]:
H

city         US                            JP          
tenor         1         3         5         1         3
0     -0.017368 -0.230016  0.805963 -1.367627  1.093190
1     -1.265274 -0.256487  1.531486 -0.785007  0.637771
2      0.454630 -0.147902  0.113548  0.891106  1.540345
3     -0.544671 -0.705411 -1.952710  0.374660  0.448362

In [109]:
H.groupby(level='city',axis=1).count()

city  JP  US
0      2   3
1      2   3
2      2   3
3      2   3

# Practice

In [1]:
import numpy as np

In [5]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
b = np.matrix([[1],[2],[3]])

In [9]:
np.linalg.solve(a,b)

matrix([[-0.23333333],
        [ 0.46666667],
        [ 0.1       ]])

In [10]:
np.__version__

'1.16.2'

In [11]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(3,2)

TypeError: data type not understood

In [16]:
np.random.normal(0,1,(4,4))

array([[-0.59207064, -0.65488772,  1.69979059,  0.77855   ],
       [ 0.36566267,  0.06475441, -1.19287814, -1.81129568],
       [-0.07346375,  0.20562892, -1.49685659, -0.98284756],
       [-0.42730761, -0.326564  ,  0.05924735,  2.43153333]])

In [19]:
np.arange(0,40,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.seed(0)

In [1]:
import numpy as np

In [14]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [1]:
x = [3,4,9,7,5,4]

In [2]:
y = [77,98,43,55,88,11]

In [5]:
x = np.array(x)

In [6]:
y = np.array(y)

In [7]:
x = np.vstack([x,np.ones(len(x))]).T

In [13]:
np.linalg.lstsq(x,y,rcond=None)[3]

array([14.18607418,  0.86907962])